const UPDATE_NOTES = 'UPDATE_NOTES';
const DELETE_NOTES = 'DELETE_NOTES';

const REQUEST_NOTES = 'REQUEST_NOTES';
const RECEIVE_NOTES = 'RECEIVE_NOTES';


export default {
    UPDATE_NOTES,
    REQUEST_NOTES,
    RECEIVE_NOTES,
    DELETE_NOTES
}